# Generated by Django 5.2.9 on 2026-07-15 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سرویس بهداشتی'),
        ),
        migrations.AddField(
            model_name='post',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AddField(
            model_name='post',
            name='capacity_base',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='ظرفیت پایه (نفر)'),
        ),
        migrations.AddField(
            model_name='post',
            name='capacity_max',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='حداکثر ظرفیت (نفر)'),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='نامشخص', max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='post',
            name='price_per_night',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت هر شب (تومان)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='توضیحات اقامتگاه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان اقامتگاه'),
        ),
    ]
