# Generated by Django 5.2.16 on 2026-08-16 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_bathrooms_post_bedrooms_post_capacity_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='bedrooms',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='capacity_base',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='capacity_max',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='گرگان', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_per_night',
            field=models.BigIntegerField(default=1200000),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('check_in', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out', models.DateField(verbose_name='تاریخ خروج')),
                ('total_price', models.BigIntegerField(default=0, verbose_name='مبلغ کل (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='blog.post', verbose_name='اقامتگاه')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
    ]
