# Generated by Django 5.2.16 on 2026-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_published_date_alter_post_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='<UNK> <UNK>'),
        ),
    ]
