# Generated by Django 5.2.16 on 2026-08-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reservation_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='updated_date',
        ),
    ]
